name: Mirror Repository

on:
  push:
    branches:
      - main # or your main branch name, you can add more branches if needed
  workflow_dispatch: # Allows manual triggering from the Actions tab on the web page

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate mirroring

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to target repository
        run: |
          TARGET_REPO="<target_github_account>/<target_repository_name>" # Replace with your target repo details
          TARGET_REPO_URL="https://${TARGET_REPO_PAT}@github.com/${TARGET_REPO}.git"

          git remote add target "$TARGET_REPO_URL"
          git push --mirror target
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
